name: Build Firefox with Custom Debugger
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Show available disk space before build
        run: Get-PSDrive -PSProvider FileSystem
