name: Build Firefox with Custom Debugger
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Show available disk space before build
        run: Get-PSDrive -PSProvider FileSystem
      - name: Create working directory
        run: |
          md -p C:\workdir
          md -p C:\workdir\mozilla-source
      - name: Copy files
        run: Copy-Item * -Destination C:\workdir
      - name: Download MozillaBuild
        working-directory: C:\workdir
        run: Invoke-WebRequest -Uri "https://ftp.mozilla.org/pub/mozilla.org/mozilla/libraries/win32/MozillaBuildSetup-Latest.exe" -OutFile "./MozillaBuildSetup-Latest.exe"
      - name: Install MozillaBuild
        working-directory: C:\workdir
        run: ./MozillaBuildSetup-Latest.exe /NCRC /S
      - name: Download bootstrap script
        working-directory: C:\workdir\mozilla-source
        run: Invoke-WebRequest -Uri "https://hg.mozilla.org/mozilla-central/raw-file/default/python/mozboot/bin/bootstrap.py" -OutFile "./bootstrap.py"
      - name: Bootstrap
        working-directory: C:\workdir\mozilla-source
        run: C:\mozilla-build\start-shell.bat -here -c "python3 bootstrap.py --application-choice 'Firefox for Desktop' --no-interactive"
        
